<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Machine" nsURI="http://fr.ubo.mde.robene.machine" nsPrefix="Machine">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MachineAbs" abstract="true">
    <eOperations name="envoieMessage" eType="#//MachineAbs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip1" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mac" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passerelle" eType="#//MachineAbs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip2" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip3" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip4" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="#//MachineAbs">
    <eOperations name="ecrireMessage" eType="#//MachineAbs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serveur" eSuperTypes="#//MachineAbs">
    <eOperations name="lanceService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propose" lowerBound="1"
        upperBound="-1" eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eOperations name="action"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AppareilReseau" eSuperTypes="#//MachineAbs">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="testConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="testConstraint" value="IP.size() > 7"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableRoutage" upperBound="-1"
        eType="#//MachineAbs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="appareilReseau" upperBound="-1"
        eType="#//AppareilReseau" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="machine" upperBound="-1"
        eType="#//Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serveur" upperBound="-1"
        eType="#//Serveur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
